# Generated by Django 3.1.7 on 2021-04-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210411_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='videoUrl',
        ),
    ]
